# -*- coding: utf-8 -*-
# vim: ft=yaml
---
wheezy:
  pkg:
    deps:
      name: linux-image-amd64

jessie:
  pkg:
    deps:
      name: linux-image-amd64

trusty:
  pkg:
    deps:
      - linux-image-extra-virtual
      - linux-image-extra-{{ grains.kernelrelease }}

precise:
  pkg:
    deps:
      - linux-image-generic-lts-raring
      - linux-headers-generic-lts-raring

CentOS Linux 7 (Core):
  pkg:
    deps:
      - yum-plugin-versionlock
      - python2-pip
      # python-docker-py https://github.com/saltstack/salt/issues/58920
      - rpmdevtools
