# -*- coding: utf-8 -*-
# vim: ft=yaml
---
FreeBSD:
  # https://reviews.freebsd.org/D21570
  pkg:
    deps:
      - devel/py-pip

Centos:
  pkg:
    deps:
      - procps
      - yum-utils

Amazon:
  pkg:
    docker:
      name: docker
      repo: null

Fedora:
  pkg:
    deps:
      - selinux-policy-minimum
      - python3-dnf-plugin-versionlock
